[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirige todas las rutas al index para el CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
